workspace '../Objective-LevelDB'
inhibit_all_warnings!

def import_pods
  pod "Objective-LevelDB", :path => "../Objective-LevelDB.podspec"
end

if ENV["TEST_ENV"] == "OSX"
  project 'Objective-LevelDB OS X Tests'
  target 'OS X Tests' do
    platform :osx, '10.9'
    import_pods
  end
else
  project 'Objective-LevelDB iOS Tests'
  target 'iOS Tests' do
    platform :ios, '7.0'
    import_pods
  end
end
